language: node_js
node_js:
- 8
notifications:
  email:
    recipients:
    - abutterworth@edx.org
    on_success: never
    on_failure: always
install:
  - npm install
script:
- npm run lint
- npm run build
after_success:
- npm run semantic-release
env:
  global:
    - secure: npInmf7b8/XckJ7tv7PnOw7zNzEKQYSJvOa+YIC+B6l0kIl7xYqYnOZUOblBuHoCxbPLXU0ErtwtF6hR7tYkZXvMCM++73X7C2IKA/VbMfbKa8/z5AkgnIb13dhuWv0ciHzuhThq39eB4UJtUIOXKxKoxEbfuidi1vaoS76PJI9Cq93WUZS8aIwgyZdhqI2j4O6s5DqVmemXmL/BCvMkNS0ok/x8O/WTqaY6v7XPzenQIKIs0OBbU3QEpTwusBud9BpninJKSKHiqBWbay0Rt1f+RhcEcR7Dwd8IK8sF524SRE1q6lCZNJmlBKnVhuYi0rT58iXK7bRVeZBAm3X5aKjLdL8aRk1t4N2r8MMz0BDGmgGj+sA3Ezy/to9Se3LLi3Vr/5huWB3xdvMY1Y182ByMFEgxLX8bOeC8Tnk60i6Pi6QaiHkyBAiugGmXsktEOdLK3XCM9FJAemhtBsb4dlhacnaS1jFWpexjmsq73ku2mgUqt48mtwu0BmC3340ewfM2S+b8e2xKw1v1JvE1cMqITOWvSqtHIZFRPpY+U1HjEVgoLA7slPDq+G14NO10MckPESBQum4QtZlE+qh0FlHtI0zWd5uSmGLsDxGs6Dk8OyXknzec1bM7LWMwuNuJyQdEB1RqwNi1UYo0lRfJ4l9HEmszZxXwmySJ92awaMg=
    - secure: mcaptZElUzMCyzo2ll4lRmcuCbqN+S/rLU0AkM3IxAw40dbPI1fFtGtKZA5EIgCu+S8MX06fzlJ15eF8vWP1d/kAUp6hBws4c9yF5M3PGhKqPSZLys5lLGq4+sWv6IyU/X9WaWiQsvt8BomnKlWhlQu0Po5f0ckDVo/36A69cxUSvII9sGZsJC82CoaaP/6672QlxXXOBepCD+OtIrQq2PGU4W41YX2uhVIxGbdxdKj/+KWbO63rdrbKcVH2gVB7NKtLHEcCDD+7GKn1yH+C6KINaa3cDZQo3q91Cv7RcjvdOL1L+j5dmiVmZRNX1QngVMGRcgsdWHhs8L/5B39e1ksnes60eeQtL6u5RhNyAylyvfN/cVaCC+DRYwpr9SFPQ51YK40BKULC7fueSOXMR1OGRXNEjRaL694vJ7KjCg4GOuxf+DZcFyABQvABcUEwKj4ayn/vWCUSyTly0VgSOxxQLtqj5WObj3asrsCAwQUJ0jAXsFP7WAAzJSheb5R1kHAkTtqp4gcn8miuujCEp4kMw6YfvmwWUb5ZrSP72QxQ3retdrPfokaThcfxfGFnzfVCOoD4DEaWTxLbPKyPcYYnpskfgEmbHiR44qEfUL/lAqBncqUgo4A02GUpCajPzOqA1vpvfE9DT8oMw4Kk37SIAKNao225EgBU3j45qDM=
